[package]
name = "users"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }

[lib]
crate-type = ["lib"]
name = "users"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
